[theme]
primaryColor = "#F0A500"
backgroundColor = "#EEF2F9"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0D2137"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
